name: Publish Docker image

on:
    push:
        branches:
        - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Create Docker network
        run: docker network create --subnet=192.168.10.0/24 network_red

      - name: Run postgresSql container
        run: |
          docker run -d --name postgres --network network_red --ip 192.168.10.35 \
          -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=D4@f7Gh#j9L$y1Pq -e POSTGRES_DB=camasprueba \
          -p 5432:5432 \
          postgres:15.0

      - name: Run eureka container
        run: |
          docker run -d --name eureka --network network_red --ip 192.168.10.35 \
          -e EUREKA_CLIENT_REGISTER_WITH_EUREKA=false -e EUREKA_CLIENT_FETCH_REGISTRY=false \
          -p 6666:6666 \
          desarrollohusjp/microservicecamas-image

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with gradle inside Docker
        run: |
          docker run --rm \
          --network network_red \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          gradle:8.10.2-jdk21-alpine \
          ./gradlew bootJar

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/microservices:asigsolcamacamillero-image .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/microservices:asigsolcamacamillero-image

      - name: Strop and remove containers
        run: |
          docker stop postgres
          docker rm postgres
          docker stop eureka
          docker rm eureka